#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : netdata
Version  : 1.41.0
Release  : 33
URL      : https://github.com/netdata/netdata/releases/download/v1.41.0/netdata-v1.41.0.tar.gz
Source0  : https://github.com/netdata/netdata/releases/download/v1.41.0/netdata-v1.41.0.tar.gz
Summary  : The CUPS metrics collection plugin for the Netdata Agent
Group    : Development/Tools
License  : Apache-2.0 Artistic-1.0 BSD-2-Clause BSD-3-Clause BSL-1.0 CC0-1.0 GPL-1.0 GPL-2.0 GPL-3.0 GPL-3.0+ LGPL-3.0 Libpng MIT
BuildRequires : Judy-dev
BuildRequires : buildreq-configure
BuildRequires : cups-dev
BuildRequires : libuv-dev
BuildRequires : lz4-dev
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(gmock)
BuildRequires : pkgconfig(grpc)
BuildRequires : pkgconfig(gtest)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(libipmimonitoring)
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnetfilter_acct)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(protobuf)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(yajl)
BuildRequires : pkgconfig(zlib)
BuildRequires : rrdtool-dev
BuildRequires : snappy-dev
BuildRequires : systemd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
netdata is the fastest way to visualize metrics. It is a resource
efficient, highly optimized system for collecting and visualizing any
type of realtime timeseries data, from CPU usage, disk activity, SQL
queries, API calls, web site visitors, etc.
  netdata tries to visualize the truth of now, in its greatest detail,
so that you can get insights of what is happening now and what just
happened, on your systems and applications.

%prep
%setup -q -n netdata-v1.41.0
cd %{_builddir}/netdata-v1.41.0
pushd ..
cp -a netdata-v1.41.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1690986536
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make
popd
%install
export SOURCE_DATE_EPOCH=1690986536
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/netdata
cp %{_builddir}/netdata-v%{version}/LICENSE %{buildroot}/usr/share/package-licenses/netdata/16f29acc74321cf07b75fbb3a318a263b71e218a || :
cp %{_builddir}/netdata-v%{version}/contrib/debian/copyright %{buildroot}/usr/share/package-licenses/netdata/b808695ed54b984a6998ca782895fb68f465455c || :
cp %{_builddir}/netdata-v%{version}/ml/dlib/dlib/LICENSE.txt %{buildroot}/usr/share/package-licenses/netdata/3f317fbb3e08fd99169d2e77105d562ea0e482c7 || :
cp %{_builddir}/netdata-v%{version}/ml/dlib/dlib/external/libpng/LICENSE %{buildroot}/usr/share/package-licenses/netdata/f2aea45b40bb8015da30997e270ecd7631a6a14d || :
cp %{_builddir}/netdata-v%{version}/ml/dlib/dlib/external/pybind11/LICENSE %{buildroot}/usr/share/package-licenses/netdata/a33b61f04391a38904373d020e7fbabf211383f6 || :
cp %{_builddir}/netdata-v%{version}/ml/dlib/docs/docs/license.xml %{buildroot}/usr/share/package-licenses/netdata/f10827e319e8d557b9ea230fbea9846ee5e7c34d || :
cp %{_builddir}/netdata-v%{version}/mqtt_websockets/LICENSE %{buildroot}/usr/share/package-licenses/netdata/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/netdata-v%{version}/mqtt_websockets/c-rbuf/LICENSE %{buildroot}/usr/share/package-licenses/netdata/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
cp %{_builddir}/netdata-v%{version}/mqtt_websockets/c_rhash/COPYING %{buildroot}/usr/share/package-licenses/netdata/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/netdata-v%{version}/mqtt_websockets/c_rhash/LICENSE %{buildroot}/usr/share/package-licenses/netdata/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/netdata-v%{version}/web/gui/v1/static/js/2.62d105c5.chunk.js.LICENSE %{buildroot}/usr/share/package-licenses/netdata/68af023f8c18dad5d0d48023109cecf405821308 || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/LICENSE %{buildroot}/usr/share/package-licenses/netdata/183197624e7e4e2df6767ed44a86fe531e93b7d1 || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/deps/brotli/LICENSE %{buildroot}/usr/share/package-licenses/netdata/00cfbd3b6e9708228a623875361a43d2e1e9314b || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/deps/mruby-input-stream/LICENSE %{buildroot}/usr/share/package-licenses/netdata/5c103e7cfbcc509830ed46db6384bb1e248dd93b || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/deps/neverbleed/LICENSE %{buildroot}/usr/share/package-licenses/netdata/c2823768370eacadd57325e509a10bd592996130 || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/deps/picotls/deps/cifra/COPYING %{buildroot}/usr/share/package-licenses/netdata/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/deps/picotls/deps/micro-ecc/LICENSE.txt %{buildroot}/usr/share/package-licenses/netdata/5b3ba9f70f16129389dd3160507407afda7bd9d5 || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/deps/ssl-conservatory/LICENSE %{buildroot}/usr/share/package-licenses/netdata/1dfac2a569f40ecb052b41d8dcecb48a1cdf2bf0 || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/deps/yaml/LICENSE %{buildroot}/usr/share/package-licenses/netdata/c01c212bdf3925189f673e2081b44094023860ea || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/misc/oktavia/LICENSE.rst %{buildroot}/usr/share/package-licenses/netdata/5b93771bfe94f1e5417f9111f02aa880472a0e7c || :
cp %{_builddir}/netdata-v%{version}/web/server/h2o/libh2o/misc/p5-Server-Starter/LICENSE %{buildroot}/usr/share/package-licenses/netdata/b91b4c6e7b5d2321318790e733a9e5c1f93c298f || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## install_append content
rm -rf %{buildroot}/var
mkdir -p %{buildroot}/usr/lib/systemd/system/
install -m 644 -p system/netdata.service "%{buildroot}/usr/lib/systemd/system/netdata.service"

## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
